### ISSUE TITLE
关于baseline在wmt17 De-En上的得分问题

### ISSUE THREAD

**Issue by XiaoqingNLP** [bzhangXMU/transformer-aan#3]
我按照您论文中的实验参数设置，使用清华的thumt 系统，基于Nvidia TiTan X ，使用wmt-17 deen 预处理好的数据，与您论文中提到的参数设置保持了高度一致，但是我的newtest2017 上detok 、大小写不敏感的得分只有31.79，与您的baseline系统相差还有一定距离，所以我想请教您是否是因为以下几个原因：
1、是否是由于您对WMT17 预处理后的德英数据进行了除BPE以外的优化处理？
2、亦或者是由于GPU型号的原因？
3、其他原因？
#### my baseline parameters with open source code THUMT
`--parameters=batch_size=3125,device_list=[1],eval_steps=5000,train_steps=100000,save_checkpoint_steps=1500,shared_embedding_and_softmax_weights=true,shared_source_target_embedding=false,             update_cycle=8`

**Comment by bzhangGo** [comment]
Hi @zxqchat,

Your question is: with the experimental settings in our paper, you only obtain a detokenized case-insensitive BLEU score of 31.79 on WMT17 De-En translation task. The dataset is  shared from the pre-processed data in WMT17 official website. Models are trained with THUMT on  Nvidia TiTan X GPU card.

Firstly, I didnot use any other resources except for the given data in the pre-processed WMT17 official package. I do not think the difference comes from the GPU card, because in my empirical experience, different cards might have different running speed, but produce similar model performance.

The most potential reason:
In the given package, except for the tokenized dataset, it also offers us a truecase model. We used this model in practice. Before BPE, we first trucases the training dataset (including both source and target corpus). After generating the translation at decoding phase, we then re-truecases it for evaluation. Perhaps you ignored this.

**Comment by XiaoqingNLP** [comment]
thank you for your answer .this file is the repositories file test.sh contents and I don't find that the re-truecase preprocess for evalutation.I will follow your tips in my expriments. 
`#! /bin/bash

data=PATH_TO_DATA #`pwd`
bin=PATH_TO_CODE #`pwd`
gpu=0

mkdir test
cd test
python ${bin}/code/thumt/scripts/checkpoint_averaging.py --path ${bin}/train --checkpoints 5 --output avg 
python ${bin}/translator.py --models transformer --input $data/dev.32k.en \
        --output dev.trans \
        --checkpoints $bin/test/avg \
        --vocabulary $data/vocab.32k.en.txt $data/vocab.32k.de.txt \
        --parameters=device_list=[$gpu]
sed "s/@@ //g" < dev.trans > dev.trans.bpe
$data/multi-bleu.perl $data/dev.de <  dev.trans.bpe >  dev.trans.bpe.nmt

python $bin/translator.py --models transformer --input $data/newstest2014.32k.en \
        --output newstest2014.trans \
        --checkpoints $bin/test/avg \
        --vocabulary $data/vocab.32k.en.txt $data/vocab.32k.de.txt \
        --parameters=device_list=[$gpu]
sed "s/@@ //g" < newstest2014.trans > newstest2014.trans.bpe
$data/multi-bleu.perl $data/newstest2014.de <  newstest2014.trans.bpe >  newstest2014.trans.bpe.nmt`

**Comment by bzhangGo** [comment]
You are right. In the given script `test.sh`, I did not provide the truecase procedure. This is because the given example is for WMT14 En-De translation task, and in this task, we typically do not perform truecase.

But for all WMT17 translation tasks, I did this using the official offered truecase model.
