### ISSUE TITLE
Why is the batch size so big?

### ISSUE THREAD

**Issue by youngkyung** [bzhangXMU/transformer-aan#7]
Now I'm testing your model with the dataset that you used by the following line;

data=data
python code/trainer.py --input $data/train.32k.en.shuf $data/train.32k.de.shuf \
        --model transformer --output train \
        --vocabulary $data/vocab.32k.en.txt $data/vocab.32k.de.txt \
        --validation $data/dev.32k.en \
        --references $data/dev.32k.de \
        --parameters=batch_size=3125,device_list=[0],eval_steps=5000,train_steps=100000,save_checkpoint_steps=1500,shared_embedding_and_softmax_weights=true,shared_source_target_embedding=false,update_cycle=8,aan_mask=True,use_ffn=False

But why is the batch size is so large like 3,125?
I found in BERT model that uses the batch size as only 16 and it was running out of memory. But in your model, it is about 3,125 and nothing happens related to memory issues. I'm curious about why you set the batch size as 3,125. 

Plus, why did you set the train steps a lot like 100,000? Compared to original BERT model, you used 10 times more train steps.

I'll look forward to your answer.
Thank you in advance.

**Comment by bzhangGo** [comment]
1. The batch_size here doe not mean the number of sentences, but the number of tokens. In other words, by 3215, it indicates 3215 tokens. When you set update_cycle to 8, there will be 8 * 3215 tokens in one batch for one training step.

2. Notice that our transformer_aan and BERT are *two different things*. 
   - Our model is used for training machine translation models, not language models. 
   - When training a BERT, you usually need a significantly larger batch_size (like 512*512 tokens) and larger training steps (like 500k steps).  And by 16, it is for fine-tuning a *pretrained* BERT rather than training from scratch.
   - For machine translation, we usually train it from scratch. In current project, I set the training steps to 100k. However, you can make it larger in order to have a better BLEU score.

**Comment by youngkyung** [comment]
Thank you for the fast reply!

Then, the reason that you used the tokens instead of sentences as unit in your model is because you train scratch, is that right?

**Comment by youngkyung** [comment]
Thank you for the fast reply!

I'm thinking about using your model in accelerating general natural language processing models not only machine translation but also language models, etc. (With citation if I succeed, of course) Do you think is that possible to accelerate such models using your method with average attention model?

**Comment by bzhangGo** [comment]
Well, I am not very sure.

Firstly, compared with self-attention, I would say average attention network is weak in terms of modeling capacity.

Secondly, language model *differs* from machine translation. In Transformer-MT, the decoder part involves both self-attention layer and encoder-decoder attention layer, and might be over-capacity.  Weakening the self-attention part does not necessarily hurt the final translation quality because of the encoder-decoder attention. In contrast, in Transformer-LM, the model totally relies on self-attention to handle word-pair correlation or dependency. The self-attention is the core of Transformer-LM. Replacing self-attention with average attention would reduce the capacity of the whole model. Though you can definitely obtain speed acceleration, you would obtain significantly worse test PPL.

Finally, If you want to work on language modeling with average attention network, one possible direction would be trying replacing part of the self-attention layers with average attention layers, and check whether the model performance is reduced (this requires experiments to verify). The assumption behind is that to get a good language model, you do not need so many self-attention layers.

Another possible direction would be using average attention network to handle context-level long-range dependency. I notice that a recent paper Transformer-XL which uses dynamic cache to handle context information. Perhaps, you can safely switch the cache to average attention network (again, experiments are required). The idea behind is that though average is simple, it could somewhat handle long or even very long sequence in a very efficient way.

**Comment by youngkyung** [comment]
According to the parameters in BERT model when it is _pre-trained_, they are used like the following;

python run_pretraining.py \
  --input_file=/tmp/tf_examples.tfrecord \
  --output_dir=/tmp/pretraining_output \
  --do_train=True \
  --do_eval=True \
  --bert_config_file=$BERT_BASE_DIR/bert_config.json \
  --init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt \
  --train_batch_size=32 \
  --max_seq_length=128 \
  --max_predictions_per_seq=20 \
  --num_train_steps=20 \
  --num_warmup_steps=10 \
  --learning_rate=2e-5

According to them, the training batch size is set as 32. Doesn't it mean that they train the model with batch size 32? Or the translation model that you used is training from scratch, so your model is tokenized and trained by dividing the tokens?

**Comment by youngkyung** [comment]
Thank you very much for your suggestions. 
I'm going to run some tests about switching self-attention layers to average attention layer with better performance!

And I'm curious whether you tried some tests also with language models. I hope it could improve the language model as well.

**Comment by bzhangGo** [comment]
1. For BERT, you'd better ask the authors rather than me. From the BERT paper, I would say the used batch size is very large.
2. LM is not my current focus and I didnot do experiments on it (though I have limited experience on running RNN-based LMs). So I can hardly tell you whether AAN works on LM or not.
3. By saying AAN is weak than self-attention, I have some empirical results by applying AAN on the encoder part of Transformer-MT and I get significantly worse BLEU. This is also verified by a recent fair paper.
